import { createBankQuestions } from "./helpers";

const pastSimpleDefinitions = [
  {
    prompt: "Choose the correct sentence: I ___ to the market yesterday.",
    correct: "I went to the market yesterday.",
    distractors: ["I go to the market yesterday.", "I goed to the market yesterday.", "I going to the market yesterday."],
    explanation: "Past Simple uses the past form of the verb for finished actions.",
    difficulty: "easy" as const,
    grammarPoint: "Past Simple affirmative — irregular verb",
    tags: ["affirmative", "time-expressions"],
  },
  {
    prompt: "Which sentence is correct?",
    correct: "She watched a movie last night.",
    distractors: ["She watch a movie last night.", "She watches a movie last night.", "She watching a movie last night."],
    explanation: "Regular verbs add -ed in Past Simple.",
    difficulty: "easy" as const,
    grammarPoint: "Past Simple affirmative — regular verb",
    tags: ["affirmative", "time-expressions"],
  },
  {
    prompt: "Choose the correct negative sentence.",
    correct: "They did not finish the test.",
    distractors: ["They did not finished the test.", "They do not finish the test.", "They not finish the test."],
    explanation: "Use did not + base verb in Past Simple negatives.",
    difficulty: "medium" as const,
    grammarPoint: "Past Simple negative — did not",
    tags: ["negative"],
  },
  {
    prompt: "Which question is correct?",
    correct: "Did you visit your cousin last week?",
    distractors: ["Did you visited your cousin last week?", "Do you visit your cousin last week?", "You did visit your cousin last week?"],
    explanation: "Past yes/no questions start with Did + subject + base verb.",
    difficulty: "medium" as const,
    grammarPoint: "Past Simple questions — did",
    tags: ["question", "yes-no", "time-expressions"],
  },
  {
    prompt: "Choose the correct wh-question.",
    correct: "Where did he put his bag?",
    distractors: ["Where did he putted his bag?", "Where does he put his bag?", "Where he did put his bag?"],
    explanation: "Wh-word + did + subject + base verb in Past Simple.",
    difficulty: "medium" as const,
    grammarPoint: "Wh-questions — where",
    tags: ["question", "wh-question"],
  },
  {
    prompt: "Which sentence uses an irregular verb correctly?",
    correct: "We ate lunch at noon.",
    distractors: ["We eat lunch at noon.", "We eated lunch at noon.", "We eating lunch at noon."],
    explanation: "Eat becomes ate in Past Simple.",
    difficulty: "easy" as const,
    grammarPoint: "Irregular verbs — eat/ate",
    tags: ["affirmative", "daily-routines"],
  },
  {
    prompt: "Choose the correct sentence with two days ago.",
    correct: "I studied English two days ago.",
    distractors: ["I study English two days ago.", "I studied English two day ago.", "I studying English two days ago."],
    explanation: "Two days ago is a common Past Simple time expression.",
    difficulty: "easy" as const,
    grammarPoint: "Time expressions — ago",
    tags: ["affirmative", "time-expressions"],
  },
  {
    prompt: "Which negative sentence is correct?",
    correct: "He didn't play football yesterday.",
    distractors: ["He didn't played football yesterday.", "He don't play football yesterday.", "He not play football yesterday."],
    explanation: "Didn't + base verb for Past Simple negatives.",
    difficulty: "medium" as const,
    grammarPoint: "Past Simple negative — didn't",
    tags: ["negative"],
  },
  {
    prompt: "Choose the correct question about time.",
    correct: "When did they arrive home?",
    distractors: ["When did they arrived home?", "When do they arrive home?", "When they did arrive home?"],
    explanation: "When + did + subject + base verb asks about past time.",
    difficulty: "medium" as const,
    grammarPoint: "Wh-questions — when",
    tags: ["question", "wh-question", "time-expressions"],
  },
  {
    prompt: "Which sentence is correct?",
    correct: "The teacher explained the rule clearly.",
    distractors: ["The teacher explain the rule clearly.", "The teacher explains the rule clearly.", "The teacher explaining the rule clearly."],
    explanation: "Explain + ed for regular Past Simple verbs.",
    difficulty: "easy" as const,
    grammarPoint: "Past Simple affirmative — regular verb",
    tags: ["affirmative"],
  },
];

export const pastSimpleQuestionBank = {
  lessonSlug: "past-simple",
  questions: createBankQuestions("past-simple", pastSimpleDefinitions),
};
