import { createBankQuestions } from "./helpers";
import type { QuestionBank } from "@/types/question-bank";

const presentSimpleDefinitions = [
  {
    prompt: "Choose the correct sentence: I ___ to school every day.",
    correct: "I go to school every day.",
    distractors: ["I goes to school every day.", "I going to school every day.", "I go to school yesterday."],
    explanation: "Use the base verb with I in Present Simple affirmative sentences.",
    difficulty: "easy" as const,
    grammarPoint: "Present Simple affirmative — I/You/We/They",
    tags: ["affirmative", "daily-routines"],
  },
  {
    prompt: "Choose the correct sentence: She ___ English very well.",
    correct: "She speaks English very well.",
    distractors: ["She speak English very well.", "She speaking English very well.", "She spoke English very well."],
    explanation: "He/She/It takes verb + s/es in Present Simple.",
    difficulty: "easy" as const,
    grammarPoint: "Third person singular -s",
    tags: ["affirmative", "daily-routines"],
  },
  {
    prompt: "Which sentence is correct?",
    correct: "They play football after school.",
    distractors: ["They plays football after school.", "They playing football after school.", "They played football after school."],
    explanation: "Plural subjects use the base verb without -s.",
    difficulty: "easy" as const,
    grammarPoint: "Present Simple affirmative — plural subject",
    tags: ["affirmative", "daily-routines"],
  },
  {
    prompt: "Complete: My brother ___ breakfast at 7 a.m.",
    correct: "My brother eats breakfast at 7 a.m.",
    distractors: ["My brother eat breakfast at 7 a.m.", "My brother eating breakfast at 7 a.m.", "My brother ate breakfast at 7 a.m."],
    explanation: "Singular third-person subjects need verb + s/es.",
    difficulty: "easy" as const,
    grammarPoint: "Third person singular -s",
    tags: ["affirmative", "daily-routines", "time-expressions"],
  },
  {
    prompt: "Which sentence shows a daily routine?",
    correct: "We brush our teeth every morning.",
    distractors: ["We brushed our teeth every morning.", "We brushing our teeth every morning.", "We brushes our teeth every morning."],
    explanation: "Present Simple describes habits and routines.",
    difficulty: "easy" as const,
    grammarPoint: "Daily routines",
    tags: ["affirmative", "daily-routines", "frequency"],
  },
  {
    prompt: "Choose the correct negative sentence.",
    correct: "I do not like spicy food.",
    distractors: ["I not like spicy food.", "I does not like spicy food.", "I do not likes spicy food."],
    explanation: "Use do not + base verb with I/You/We/They.",
    difficulty: "medium" as const,
    grammarPoint: "Present Simple negative — do not",
    tags: ["negative", "do-does"],
  },
  {
    prompt: "Choose the correct negative sentence.",
    correct: "She does not watch TV on weekdays.",
    distractors: ["She do not watch TV on weekdays.", "She does not watches TV on weekdays.", "She not watch TV on weekdays."],
    explanation: "Use does not + base verb with He/She/It.",
    difficulty: "medium" as const,
    grammarPoint: "Present Simple negative — does not",
    tags: ["negative", "do-does", "daily-routines"],
  },
  {
    prompt: "Which negative sentence is correct?",
    correct: "They do not live near the school.",
    distractors: ["They does not live near the school.", "They do not lives near the school.", "They not live near the school."],
    explanation: "Plural subjects use do not, not does not.",
    difficulty: "medium" as const,
    grammarPoint: "Present Simple negative — plural",
    tags: ["negative", "do-does"],
  },
  {
    prompt: "Choose the correct short negative.",
    correct: "He doesn't play the guitar.",
    distractors: ["He don't play the guitar.", "He doesn't plays the guitar.", "He not play the guitar."],
    explanation: "Doesn't = does not; the main verb stays in base form.",
    difficulty: "medium" as const,
    grammarPoint: "Contractions — doesn't",
    tags: ["negative", "do-does"],
  },
  {
    prompt: "Which sentence is a correct yes/no question?",
    correct: "Do you study English every day?",
    distractors: ["Does you study English every day?", "Do you studies English every day?", "You do study English every day?"],
    explanation: "Start with Do + subject + base verb for I/You/We/They.",
    difficulty: "medium" as const,
    grammarPoint: "Yes/No questions — do",
    tags: ["question", "yes-no", "do-does", "daily-routines"],
  },
  {
    prompt: "Which sentence is a correct yes/no question?",
    correct: "Does she walk to work?",
    distractors: ["Do she walk to work?", "Does she walks to work?", "She does walk to work?"],
    explanation: "Start with Does + subject + base verb for He/She/It.",
    difficulty: "medium" as const,
    grammarPoint: "Yes/No questions — does",
    tags: ["question", "yes-no", "do-does"],
  },
  {
    prompt: "Choose the correct wh-question.",
    correct: "What do you do after school?",
    distractors: ["What does you do after school?", "What do you does after school?", "What you do after school?"],
    explanation: "Wh-word + do/does + subject + base verb.",
    difficulty: "medium" as const,
    grammarPoint: "Wh-questions — what",
    tags: ["question", "wh-question", "do-does", "daily-routines"],
  },
  {
    prompt: "Choose the correct wh-question.",
    correct: "Where does he keep his books?",
    distractors: ["Where do he keep his books?", "Where does he keeps his books?", "Where he does keep his books?"],
    explanation: "Use does with he/she/it in wh-questions.",
    difficulty: "medium" as const,
    grammarPoint: "Wh-questions — where",
    tags: ["question", "wh-question", "do-does"],
  },
  {
    prompt: "Which question asks about time correctly?",
    correct: "When do they start class?",
    distractors: ["When does they start class?", "When do they starts class?", "When they start class?"],
    explanation: "When + do/does + subject + base verb asks about time.",
    difficulty: "medium" as const,
    grammarPoint: "Wh-questions — when",
    tags: ["question", "wh-question", "time-expressions"],
  },
  {
    prompt: "Choose the correct question about frequency.",
    correct: "How often do you exercise?",
    distractors: ["How often does you exercise?", "How often do you exercises?", "How often you exercise?"],
    explanation: "How often asks about frequency with Present Simple.",
    difficulty: "medium" as const,
    grammarPoint: "Frequency questions",
    tags: ["question", "wh-question", "frequency"],
  },
  {
    prompt: "Which sentence uses an adverb of frequency correctly?",
    correct: "I usually finish my homework before dinner.",
    distractors: ["I finish usually my homework before dinner.", "I usual finish my homework before dinner.", "I usually finishes my homework before dinner."],
    explanation: "Adverbs of frequency usually go before the main verb.",
    difficulty: "medium" as const,
    grammarPoint: "Adverbs of frequency — usually",
    tags: ["adverbs", "frequency", "daily-routines"],
  },
  {
    prompt: "Which sentence uses never correctly?",
    correct: "She never eats fast food.",
    distractors: ["She eats never fast food.", "She never eat fast food.", "Never she eats fast food."],
    explanation: "Never goes before the main verb in Present Simple.",
    difficulty: "medium" as const,
    grammarPoint: "Adverbs of frequency — never",
    tags: ["adverbs", "frequency", "negative"],
  },
  {
    prompt: "Choose the sentence with always in the correct position.",
    correct: "They always help their classmates.",
    distractors: ["They help always their classmates.", "They always helps their classmates.", "Always they help their classmates."],
    explanation: "Always comes before the main verb but after be (if used).",
    difficulty: "easy" as const,
    grammarPoint: "Adverbs of frequency — always",
    tags: ["adverbs", "frequency"],
  },
  {
    prompt: "Which sentence shows a time expression correctly?",
    correct: "We have lunch at 12:30.",
    distractors: ["We has lunch at 12:30.", "We having lunch at 12:30.", "We have lunch on 12:30."],
    explanation: "Use at with clock times.",
    difficulty: "easy" as const,
    grammarPoint: "Time expressions — at + clock time",
    tags: ["time-expressions", "daily-routines"],
  },
  {
    prompt: "Which sentence uses on correctly?",
    correct: "He plays football on Saturdays.",
    distractors: ["He plays football in Saturdays.", "He play football on Saturdays.", "He plays football at Saturdays."],
    explanation: "Use on with days of the week.",
    difficulty: "easy" as const,
    grammarPoint: "Time expressions — on + day",
    tags: ["time-expressions", "daily-routines"],
  },
  {
    prompt: "Choose the correct sentence with every.",
    correct: "I read books every night.",
    distractors: ["I reads books every night.", "I read books in every night.", "I reading books every night."],
    explanation: "Every + time period shows repeated habits.",
    difficulty: "easy" as const,
    grammarPoint: "Frequency — every",
    tags: ["frequency", "daily-routines", "time-expressions"],
  },
  {
    prompt: "Which sentence uses once a week correctly?",
    correct: "She visits her grandma once a week.",
    distractors: ["She visit her grandma once a week.", "She visits her grandma one a week.", "She visiting her grandma once a week."],
    explanation: "Once a week describes how often something happens.",
    difficulty: "medium" as const,
    grammarPoint: "Frequency — once a week",
    tags: ["frequency", "daily-routines"],
  },
  {
    prompt: "Choose the correct affirmative with he.",
    correct: "He drinks milk every morning.",
    distractors: ["He drink milk every morning.", "He drinks milk every mornings.", "He drinking milk every morning."],
    explanation: "He/She/It verbs often add -s in Present Simple.",
    difficulty: "easy" as const,
    grammarPoint: "Third person singular -s",
    tags: ["affirmative", "daily-routines"],
  },
  {
    prompt: "Which sentence is correct?",
    correct: "The cat sleeps on the sofa.",
    distractors: ["The cat sleep on the sofa.", "The cat sleeping on the sofa.", "The cat sleeps in the sofa."],
    explanation: "Singular nouns like the cat take verb + s.",
    difficulty: "easy" as const,
    grammarPoint: "Third person singular — singular noun",
    tags: ["affirmative"],
  },
  {
    prompt: "Choose the correct question: ___ your parents live in Bangkok?",
    correct: "Do your parents live in Bangkok?",
    distractors: ["Does your parents live in Bangkok?", "Do your parents lives in Bangkok?", "Your parents do live in Bangkok?"],
    explanation: "Plural subject your parents uses Do.",
    difficulty: "medium" as const,
    grammarPoint: "Yes/No questions — plural subject",
    tags: ["question", "yes-no", "do-does"],
  },
  {
    prompt: "Which wh-question is correct?",
    correct: "Why do we practice English every day?",
    distractors: ["Why does we practice English every day?", "Why do we practices English every day?", "Why we practice English every day?"],
    explanation: "Why + do/does + subject + base verb asks for a reason.",
    difficulty: "hard" as const,
    grammarPoint: "Wh-questions — why",
    tags: ["question", "wh-question", "frequency"],
  },
  {
    prompt: "Choose the correct negative with they.",
    correct: "They don't eat meat.",
    distractors: ["They doesn't eat meat.", "They don't eats meat.", "They not eat meat."],
    explanation: "They uses don't (do not) + base verb.",
    difficulty: "medium" as const,
    grammarPoint: "Contractions — don't",
    tags: ["negative", "do-does"],
  },
  {
    prompt: "Which sentence uses sometimes correctly?",
    correct: "I sometimes ride a bike to school.",
    distractors: ["I ride sometimes a bike to school.", "I sometimes rides a bike to school.", "Sometimes I riding a bike to school."],
    explanation: "Sometimes can go before the main verb or at the start of a sentence.",
    difficulty: "medium" as const,
    grammarPoint: "Adverbs of frequency — sometimes",
    tags: ["adverbs", "frequency", "daily-routines"],
  },
  {
    prompt: "Choose the correct sentence with watches.",
    correct: "He watches cartoons on Sunday.",
    distractors: ["He watch cartoons on Sunday.", "He watches cartoon on Sunday.", "He watching cartoons on Sunday."],
    explanation: "Watch + es after ch/sh/x/s/o.",
    difficulty: "medium" as const,
    grammarPoint: "Spelling — watch → watches",
    tags: ["affirmative", "time-expressions"],
  },
  {
    prompt: "Which sentence uses do correctly in a question?",
    correct: "Do they clean the classroom after lunch?",
    distractors: ["Does they clean the classroom after lunch?", "Do they cleans the classroom after lunch?", "They do clean the classroom after lunch?"],
    explanation: "They requires Do at the start of yes/no questions.",
    difficulty: "medium" as const,
    grammarPoint: "Yes/No questions — they",
    tags: ["question", "yes-no", "do-does", "daily-routines"],
  },
  {
    prompt: "Choose the correct answer form: Do you like pizza? — Yes, I ___.",
    correct: "Yes, I do.",
    distractors: ["Yes, I like.", "Yes, I does.", "Yes, I am."],
    explanation: "Short answers repeat do/does, not the main verb.",
    difficulty: "easy" as const,
    grammarPoint: "Short answers — yes/no",
    tags: ["yes-no", "question"],
  },
  {
    prompt: "Choose the correct short answer: Does she swim well? — No, she ___.",
    correct: "No, she doesn't.",
    distractors: ["No, she don't.", "No, she isn't.", "No, she doesn't swimn't."],
    explanation: "Short negative answers use doesn't for he/she/it.",
    difficulty: "easy" as const,
    grammarPoint: "Short answers — doesn't",
    tags: ["yes-no", "question", "negative"],
  },
  {
    prompt: "Which sentence uses every day correctly?",
    correct: "We walk to school every day.",
    distractors: ["We walks to school every day.", "We walk to school every days.", "We walking to school every day."],
    explanation: "Every day = each day; day stays singular.",
    difficulty: "easy" as const,
    grammarPoint: "Frequency — every day",
    tags: ["frequency", "daily-routines"],
  },
  {
    prompt: "Choose the correct wh-question about a person.",
    correct: "Who do you sit with in class?",
    distractors: ["Who does you sit with in class?", "Who do you sits with in class?", "Who you sit with in class?"],
    explanation: "Who asks about a person; use do/does + base verb.",
    difficulty: "hard" as const,
    grammarPoint: "Wh-questions — who",
    tags: ["question", "wh-question"],
  },
  {
    prompt: "Which sentence is a correct Present Simple fact?",
    correct: "The sun rises in the east.",
    distractors: ["The sun rise in the east.", "The sun rising in the east.", "The sun rised in the east."],
    explanation: "Present Simple also describes general truths and facts.",
    difficulty: "easy" as const,
    grammarPoint: "General truths",
    tags: ["affirmative"],
  },
  {
    prompt: "Choose the correct negative with I.",
    correct: "I don't wake up late on school days.",
    distractors: ["I doesn't wake up late on school days.", "I don't wakes up late on school days.", "I not wake up late on school days."],
    explanation: "I uses don't + base verb in negatives.",
    difficulty: "medium" as const,
    grammarPoint: "Negative — I don't",
    tags: ["negative", "do-does", "daily-routines"],
  },
  {
    prompt: "Which question asks about place correctly?",
    correct: "Where do you keep your dictionary?",
    distractors: ["Where does you keep your dictionary?", "Where do you keeps your dictionary?", "Where you keep your dictionary?"],
    explanation: "Where + do + you + base verb asks about place.",
    difficulty: "medium" as const,
    grammarPoint: "Wh-questions — where",
    tags: ["question", "wh-question"],
  },
  {
    prompt: "Which sentence uses rarely correctly?",
    correct: "He rarely forgets his homework.",
    distractors: ["He forgets rarely his homework.", "He rarely forget his homework.", "Rarely he forgets his homework."],
    explanation: "Rarely is an adverb of frequency placed before the main verb.",
    difficulty: "hard" as const,
    grammarPoint: "Adverbs of frequency — rarely",
    tags: ["adverbs", "frequency"],
  },
  {
    prompt: "Which sentence uses in the morning correctly?",
    correct: "They read the news in the morning.",
    distractors: ["They reads the news in the morning.", "They read the news on the morning.", "They reading the news in the morning."],
    explanation: "Use in with parts of the day like in the morning.",
    difficulty: "easy" as const,
    grammarPoint: "Time expressions — in the morning",
    tags: ["time-expressions", "daily-routines"],
  },
  {
    prompt: "Choose the correct question with how often.",
    correct: "How often does your teacher give homework?",
    distractors: ["How often do your teacher give homework?", "How often does your teacher gives homework?", "How often your teacher gives homework?"],
    explanation: "Singular your teacher uses does in questions.",
    difficulty: "hard" as const,
    grammarPoint: "Frequency questions — singular subject",
    tags: ["question", "wh-question", "frequency", "do-does"],
  },
  {
    prompt: "Which affirmative sentence is correct?",
    correct: "You play the piano very well.",
    distractors: ["You plays the piano very well.", "You playing the piano very well.", "You play the piano very good."],
    explanation: "You takes the base verb without -s.",
    difficulty: "easy" as const,
    grammarPoint: "Present Simple — you",
    tags: ["affirmative"],
  },
  {
    prompt: "Choose the correct negative with it.",
    correct: "It does not rain much here.",
    distractors: ["It do not rain much here.", "It does not rains much here.", "It not rain much here."],
    explanation: "It uses does not + base verb.",
    difficulty: "medium" as const,
    grammarPoint: "Negative — it does not",
    tags: ["negative", "do-does"],
  },
  {
    prompt: "Which question is correct?",
    correct: "Do we need a pencil for this activity?",
    distractors: ["Does we need a pencil for this activity?", "Do we needs a pencil for this activity?", "We do need a pencil for this activity?"],
    explanation: "We uses Do in yes/no questions.",
    difficulty: "medium" as const,
    grammarPoint: "Yes/No questions — we",
    tags: ["question", "yes-no", "do-does"],
  },
  {
    prompt: "Choose the sentence with twice a day.",
    correct: "I brush my teeth twice a day.",
    distractors: ["I brushes my teeth twice a day.", "I brush my teeth two times a day.", "I brushing my teeth twice a day."],
    explanation: "Twice a day shows frequency in Present Simple routines.",
    difficulty: "medium" as const,
    grammarPoint: "Frequency — twice a day",
    tags: ["frequency", "daily-routines"],
  },
  {
    prompt: "Which wh-question asks about method?",
    correct: "How do you get to school?",
    distractors: ["How does you get to school?", "How do you gets to school?", "How you get to school?"],
    explanation: "How asks about manner or method with do/does.",
    difficulty: "medium" as const,
    grammarPoint: "Wh-questions — how",
    tags: ["question", "wh-question", "daily-routines"],
  },
  {
    prompt: "Choose the correct sentence with fixes.",
    correct: "My dad fixes bikes on weekends.",
    distractors: ["My dad fix bikes on weekends.", "My dad fixing bikes on weekends.", "My dad fixes bikes in weekends."],
    explanation: "Fix + es after x/s/ch/sh; on weekends is a time expression.",
    difficulty: "medium" as const,
    grammarPoint: "Spelling — fix → fixes",
    tags: ["affirmative", "time-expressions", "daily-routines"],
  },
  {
    prompt: "Which negative sentence is correct?",
    correct: "We do not use phones in class.",
    distractors: ["We does not use phones in class.", "We do not uses phones in class.", "We not use phones in class."],
    explanation: "We uses do not + base verb in negatives.",
    difficulty: "medium" as const,
    grammarPoint: "Negative — we do not",
    tags: ["negative", "do-does"],
  },
  {
    prompt: "Choose the correct question with what time.",
    correct: "What time do you go to bed?",
    distractors: ["What time does you go to bed?", "What time do you goes to bed?", "What time you go to bed?"],
    explanation: "What time asks about clock time with Present Simple.",
    difficulty: "hard" as const,
    grammarPoint: "Wh-questions — what time",
    tags: ["question", "wh-question", "time-expressions"],
  },
  {
    prompt: "Which sentence uses often correctly?",
    correct: "She often listens to English songs.",
    distractors: ["She listens often to English songs.", "She often listen to English songs.", "Often she listening to English songs."],
    explanation: "Often usually comes before the main verb.",
    difficulty: "medium" as const,
    grammarPoint: "Adverbs of frequency — often",
    tags: ["adverbs", "frequency"],
  },
  {
    prompt: "Choose the correct affirmative with they and at night.",
    correct: "They study quietly at night.",
    distractors: ["They studys quietly at night.", "They studying quietly at night.", "They study quietly in night."],
    explanation: "They + base verb; at night is a common time expression.",
    difficulty: "easy" as const,
    grammarPoint: "Time expressions — at night",
    tags: ["affirmative", "time-expressions", "daily-routines"],
  },
];

export const presentSimpleQuestionBank = {
  lessonSlug: "present-simple",
  questions: createBankQuestions("present-simple", presentSimpleDefinitions),
};
